name: docs

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    if: ${{ vars.DOCS_WORKFLOW_ENABLED == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install MkDocs and theme
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Build & deploy (gh-pages)
        run: mkdocs gh-deploy --force
